title: Geolonia PWAマップ
description: Google スプレッドシートを更新するだけでオリジナルの地図アプリを作成できる「Geolonia PWAマップ」
hosting_url: https://naogify.github.io/pwamap_v2/
data_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vTBoxWsfjJm9V9kSwviXq7F5V9fULa0BNhZRvmub5pOxwPTyD0STUetwqKpk-oykUXqE601ekUVA1RR/pub?output=csv
